Parameters:
  # Existing Bucket name
  PipelineID:
    Description: Existing Bucket name
    Type: String
Resources:
  cloudfrontOAI
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        CloudFrontOriginAccessIdentityConfig
        
 webpagecdn
  Type: AWS::CloudFront::Distribution
  Properties:
    DistributionConfig:
     Origins: 
           - DomainName: !Sub "${PipelineID}.s3.amazonaws.com"
             Id: webpage
             S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${cloudfrontOAI}"     
     Enabled: True
     DefaultRootObject: index.html
     DefaultCacheBehavior:
       ForwardedValues:
          QueryString: False
       TargetOriginId: webpage
       ViewerProtocolPolicy: allow-all    
